// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaBoletos.Models;

#nullable disable

namespace SistemaBoletos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("SistemaBoletos.Models.Cooperativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoletosVendidos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacidadMaxima")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cooperativas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BoletosVendidos = 0,
                            CapacidadMaxima = 45,
                            Nombre = "Imbaburapac"
                        },
                        new
                        {
                            Id = 2,
                            BoletosVendidos = 0,
                            CapacidadMaxima = 2147483647,
                            Nombre = "Lagos"
                        });
                });

            modelBuilder.Entity("SistemaBoletos.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Edad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("SistemaBoletos.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AplicaComision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadBoletos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CooperativaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CooperativaId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("SistemaBoletos.Models.Venta", b =>
                {
                    b.HasOne("SistemaBoletos.Models.Cooperativa", "Cooperativa")
                        .WithMany()
                        .HasForeignKey("CooperativaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaBoletos.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cooperativa");

                    b.Navigation("Persona");
                });
#pragma warning restore 612, 618
        }
    }
}
